name: Gh-Pages

on:
  push:
    branches: [ myspaceshoot ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.15.0
        with:
          flutter-version: '3.22.2'  # 可以根据需要指定 Flutter 版本

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --web-renderer canvaskit

      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /spaceshoot/
          webRenderer: canvaskit
